### ISSUE TITLE
Proxy issue with  Harmony-reflect

### ISSUE THREAD

**Issue by zackleman** [Q42/DDP-Server-Reactive#1]
The following sample code throws the following error. I am currenty running this as a test on my mac. How can this be resolved? Thanks.

```
^Cdhcp-213-86:peer zackleman$ node index.js
Hello World

/Users/zackleman/Desktop/peer/node_modules/ddp-server-reactive/node_modules/harmony-reflect/reflect.js:1992
    throw new Error("proxies not supported on this platform");
          ^
Error: proxies not supported on this platform
    at global.Proxy (/Users/zackleman/Desktop/peer/node_modules/ddp-server-reactive/node_modules/harmony-reflect/reflect.js:1992:11)
    at publish (/Users/zackleman/Desktop/peer/node_modules/ddp-server-reactive/lib.js:211:32)
    at Object.<anonymous> (/Users/zackleman/Desktop/peer/index.js:33:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

```
var sys = require("sys");
var DDPServer = require("ddp-server-reactive");




// Create a server listening on the default port 3000
var server = new DDPServer();
 sys.puts("Hello World");

// Create a reactive collection
// All the changes below will automatically be sent to subscribers
var todoList = server.publish("todolist");

// Add items
todoList[0] = { title: "Cook dinner", done: false };
todoList[1] = { title: "Water the plants", done: true };

// Change items
todoList[0].done = true;
 sys.puts(todoList);
// Remove items
delete todoList[1]

// Add methods
server.methods({
  test: function() {
    return true;
  }
});

```

**Comment by sjoerdvisscher** [comment]
Node does not enable proxies by default, you need to run it like this:

`node --harmony_proxies`

**Comment by aseds** [comment]
**i used the flag but...**

the server.js file:

```
var DDPServer = require('ddp-server-reactive');

var server = new DDPServer();



var todoList = server.publish('todolist');
```

command-line:

```
[aseds@localhost ~]$ node server.js --harmony_proxies
/home/aseds/Desktop/projeh/css-goodness/node_modules/harmony-reflect/reflect.js:2049
      throw new Error("proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag");
      ^

Error: proxies not supported on this platform. On v8/node/iojs, make sure to pass the --harmony_proxies flag
    at global.Proxy (/home/aseds/Desktop/projeh/css-goodness/node_modules/harmony-reflect/reflect.js:2049:13)
    at publish (/home/aseds/Desktop/projeh/css-goodness/node_modules/ddp-server-reactive/lib.js:211:32)
    at Object.<anonymous> (/home/aseds/Desktop/projeh/css-goodness/ddpserver.js:10:23)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3

```

```
[aseds@localhost ~]$ node -v
v5.4.1
```

**Comment by sjoerdvisscher** [comment]
Hmm, I don't know, this is an issue for the harmony-reflect package really.
I'll try it on v5.4.1 when I have the time to see if I can reproduce the issue.
